



import type { Metadata } from "next";

import Container from "@/src/components/modules/UI/container";
import Sidebar from "@/src/components/modules/UI/Sidebar";




export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container>
      <div className="flex justify-between">
        <div className="w-[20%] bg-default-100 rounded-xl">
          <Sidebar />
        </div>
        <div className="w-[80%] bg-default-100 rounded-xl ml-2">{children}</div>
      </div>
    </Container>
  );
}
